name: 'GitLab Pipeline Action'
description: 'Run a GitLab pipeline from within GitHub actions'
inputs:
  GL_SERVER_URL:
    description: 'Host of the GitLab server'
    required: true
    default: 'https://gitlab.com'
  GL_PROJECT_ID:
    description: 'ID of the GitLab project'
    required: true
  GL_RUNNER_TOKEN:
    description: 'A runner token, if a runner should be started in this action'
  GL_API_TOKEN:
    description: 'A token to check the pipeline status with'
    required: true
  SHOW_JOB_LOGS:
    description: 'Set if the job log should be shown in the action output'
    default: 'none'

  TASK:
    description: 'Specify the task to run'
    default: 'gitlab_pipeline_action'

  # Overrides of default variables
  OVERRIDE_GITHUB_SHA:
    description: 'Override the git sha given from GitHub'
  OVERRIDE_GITHUB_REF:
    description: 'Override the git ref given from GitHub. Should be in format "refs/<type>/<name>"'
  OVERRIDE_GITHUB_REF_NAME:
    description: 'Override the git ref name given from GitHub'
outputs:
  SUMMARY_TEXT:
    description: 'Markdown content of the action summary'
  PIPELINE_ID:
    description: 'ID of the triggered pipeline on GitLab'
author: 'Taucher2003'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/taucher2003/gitlab-pipeline-action:1.6.5'
  args:
    - /gitlab_pipeline_action/bin/${{ inputs.TASK }}.rb
branding:
  icon: check-circle
  color: orange
