name: Run Integration test

on:
  push:
  pull_request:

jobs:
  integration-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gitlab_version:
          - 16.5.2-ce.0
          - 16.4.2-ce.0
          - 16.3.6-ce.0

    steps:
      - uses: actions/checkout@v4
      - run: GITLAB_CE_VERSION=${{ matrix.gitlab_version }} docker compose up -d
        working-directory: test
      - run: test/await_healthy.sh
      - uses: ./
        name: Run test
        with:
          GL_SERVER_URL: http://172.17.0.1:8080
          GL_PROJECT_ID: '1000'
          GL_RUNNER_TOKEN: some_long_runner_token
          GL_API_TOKEN: TEST1234567890123456
      - run: 'curl --silent --header "Private-Token: TEST1234567890123456" "http://127.17.0.1:8080/api/v4/projects/1000/jobs/1/trace"'
        if: always()
      - run: docker compose down
        if: always()
        working-directory: test
