name: Run Tests

on:
  push:
  pull_request:

jobs:
  integration-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gitlab_version:
          - 17.3.1-ce.0
          - 17.2.4-ce.0
          - 17.1.6-ce.0

    steps:
      - uses: actions/checkout@v4
      - run: GITLAB_CE_VERSION=${{ matrix.gitlab_version }} docker compose up -d
        working-directory: test
      - run: test/await_healthy.sh
      - uses: ./
        name: Run smoke-test (running the action)
        with:
          GL_SERVER_URL: http://172.17.0.1:8080
          GL_PROJECT_ID: '1000'
          GL_RUNNER_TOKEN: some_long_runner_token
          GL_API_TOKEN: TEST1234567890123456
          SHOW_JOB_LOGS: all
        env:
          GLPA_SOME_VARIABLE: some value for the variable
      - run: 'curl --silent --header "Private-Token: TEST1234567890123456" "http://127.17.0.1:8080/api/v4/projects/1000/jobs/1/trace"'
        if: always()
      - uses: ruby/setup-ruby@v1
      - run: bundle install
      - run: bundle exec rspec
        name: Run tests (running rspec)
        env:
          GITLAB_BASE_URL_FOR_RUNNER: http://172.17.0.1:8080
      - run: docker compose down
        if: always()
        working-directory: test

  rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
      - run: bundle install
      - run: bundle exec rubocop
